on:
  push:
    branches:
      main
  
name: Render-Book-from-main

jobs:
  quarto:
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          version: pre-release
        
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2